#
# data-engineering-zoomcamp
# Week 1 - Homework
# Docker Compose
# 

version: "3"
services:
  db:
    image: postgres:14.4-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  ingest:
    env_file: .env
    build: .
    volumes:
      - ./data:/data
volumes:
  db-data: {}
